### ISSUE TITLE
Week of 2022/02/14 deploys

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#1373]
`staging-intl`, `stg-us-facil` and `stg-us-pha` are all ahead of `prod-intl` and `prod-us` right now (which is fine). We have a couple of pending PRs that want to be merged and released (#1297, #1365). I plan to:

**Catch `prod-us` and `prod-intl` up with `stg-us`**
* [x] merge #1374 to bump prod env containers to 0.6.24
* [x] deploy containers 0.6.24/Terraform git sha `2728b433d8d3ed8dafe9b8aa09a5fdd4eddef56e` to `prod-intl`
* [x] deploy containers 0.6.24/Terraform git sha `2728b433d8d3ed8dafe9b8aa09a5fdd4eddef56e` to `prod-us`

**Deploy the next thing to `stg-us` and `staging-intl`**
* [x] merge #1297 and #1365 to `main`
* [x] cut a release ([0.6.25](https://github.com/abetterinternet/prio-server/releases/tag/0.6.25)) with those changes
* [x] merge #1383 to bump `staging-intl`, `stg-us-pha`, `stg-us-facil` to 0.6.25 containers
* [x] perform manual `vpc-cni` addon updates in `staging-intl` and `stg-us-pha` as needed
* [x] deploy containers 0.6.25/Terraform git SHA ccc65df81ee6d4dddac64f0ebcd3626663d542a5 to `staging-intl` (including EKS cluster update)
* [x] deploy containers 0.6.25/Terraform git SHA ccc65df81ee6d4dddac64f0ebcd3626663d542a5 to `stg-us-pha` (including EKS cluster update)
* [x] deploy containers 0.6.25/Terraform git SHA ccc65df81ee6d4dddac64f0ebcd3626663d542a5 to  `stg-us-facil`

**(Thursday) Deploy the next thing to `prod-us` and `prod-intl`**
* [x] perform manual `vpc-cni` addon updates in `prod-intl` as needed
* [x] deploy containers 0.6.25/Terraform git SHA 16221d244f1b9bfe49780e5bce98e28a1c4768e9 to `prod-us`
* [x] deploy containers 0.6.25/Terraform git SHA 16221d244f1b9bfe49780e5bce98e28a1c4768e9 to `prod-intl` (includes EKS cluster update for).

**Comment by tgeoghegan** [comment]
In order to update `staging-intl` and `stg-us-pha` to EKS v1.21, I had to manually update the `vpc-cni` plugin from v1.7.5 (what was deployed) through v1.8.0 and v1.9.3, to then have Terraform deploy v1.10.0. See <todo terraform/README.md link> for details.

**Comment by BranLwyd** [comment]
> I halted the `prod-intl` deployment because It would include the following change to `key-rotator` jobs:
> 
> ```
> - "--default-manifest-by-ingestor={\"apple\":{\"format\":1,\"ingestion-bucket\":\"gs://prio-prod-us-us-ca-apple-ingestion\",\"ingestion-identity\":null,\"peer-validation-bucket\":\"gs://prio-prod-us-us-ca-apple-peer-validation\",\"peer-validation-identity\":null},\"g-enpa\":{\"format\":1,\"ingestion-bucket\":\"gs://prio-prod-us-us-ca-g-enpa-ingestion\",\"ingestion-identity\":null,\"peer-validation-bucket\":\"gs://prio-prod-us-us-ca-g-enpa-peer-validation\",\"peer-validation-identity\":null}}",
> + "--default-manifest-by-ingestor={\"apple\":{\"format\":2,\"ingestion-bucket\":\"gs://prio-prod-us-us-ca-apple-ingestion\",\"ingestion-identity\":null,\"peer-validation-bucket\":\"gs://prio-prod-us-us-ca-apple-peer-validation\",\"peer-validation-identity\":null},\"g-enpa\":{\"format\":2,\"ingestion-bucket\":\"gs://prio-prod-us-us-ca-g-enpa-ingestion\",\"ingestion-identity\":null,\"peer-validation-bucket\":\"gs://prio-prod-us-us-ca-g-enpa-peer-validation\",\"peer-validation-identity\":null}}",
> ```
> 
> The important thing there is specific manifests going from version `1` to version `2`. I'm not sure we want to do that until we are confident that our NCI counterpart is running a `facilitator` that can read that format version. I think it should be OK but I would like @BranLwyd to double confirm before we proceed.

NIH is on a version that can read DSP-specific manifest v2. [also, though this would be small comfort if NIH could not read these manifests, the `key-rotator` would only export these manifests if the existing manifest was missing]


I noticed something strange while investigating this: even v1 manifests were specifying `peer-validation-identity` in the Terraform (as `null`). But this field doesn't exist on the relevant Rust struct, and `deny_unknown_fields` is specified. I confirmed by going back to the 0.6.19 commit & updating a test that specifying `peer-validation-identity` does indeed block parsing, even with a `null` value. My best guess as to why we haven't run into this is that we haven't deployed to a new locality since the v2 manifest was introduced last July? In any case -- migrating to v2 actually _fixes_ this issue, as does merging the two versions (unintentionally, in both cases).

**Comment by tgeoghegan** [comment]
Completed the deploys to prod-us and prod-intl -- closing.
